rudderlabs/rudderstack-profiles-classifier

conda_env.yml
requirements.txt

chore: update snowflake_connector_python version to fix vulnerability

---

conda_env.yml
requirements.txt

chore: update snowflake_connector_python version

---

config/data_prep.yaml
predict.py
requirements.txt
train.py
utils.py

adding feature importance curve

---

train.py

modified:   train.py
> converted the timestamp format that is to be saved in training_summary file as UTC timezone.

timezone converted to standard UTC timezone format

---

requirements.txt
train.py
utils.py

modified:   requirements.txt
modified:   train.py
modified:   utils.py
> Standardised the ROC-AUC, PR-AUC, Lift-chart and feature-importance-chart.
> Added seaborn==0.12.0 in requirements file.
> Written different function for creating graphs.
> Save the figures to stage inside UDF and extracted to local later.
> Added prefixes 01, 02, 03 and 04 to ROC-AUC, PR-AUC, Lift-chart and feature-importance-chart respectively so that UI can pick these in same order.

standardised the output images

---

predict.py

modified:   predict.py
> removed predict_path from imports in predict script.

resolved caching for predict script

---

train.py
utils.py

modified:   train.py
modified:   utils.py
> Deleted all the previous procedures whose names were starting with trained procedure name.

Deleting previous trained procedures

---

utils.py

fixing bug related to getting old timestamps automatically.

---

config/data_prep.yaml
predict.py
train.py
utils.py

modified:   config/data_prep.yaml
modified:   train.py
modified:   utils.py
> We have considered the case where timestamp columns are taken automatically if not given.

taking timestamp column automatically

---

utils.py

modified:   utils.py
> changing path to make it work on windows.

changing path to make it work on windows

---

Dockerfile
src/processors/K8sProcessor.py

https://linear.app/rudderstack/issue/PRML-389/add-job-completion-check-in-k8-processor
> Fix [#1]()

feat: add job status check in k8s processor

---

requirements.txt

fix: remove google-cloud-bigquery from requirements.txt

---

src/utils/constants.py
src/utils/utils.py

fix: hardcode pb path

---

src/ml_core/preprocess_and_train.py
src/processors/AWSProcessor.py
src/processors/LocalProcessor.py
src/processors/Processor.py
src/processors/SnowflakeProcessor.py

modified:   src/ml_core/preprocess_and_train.py
modified:   src/processors/AWSProcessor.py
modified:   src/processors/LocalProcessor.py
modified:   src/processors/Processor.py
modified:   src/processors/SnowflakeProcessor.py
> Fix [#1]()

trigger preprocess and train script in local mode

---

.gitignore
scripts/simulate_pb_run.py
src/connectors/Connector.py
src/connectors/RedshiftConnector.py
src/connectors/SnowflakeConnector.py
src/connectors/wh/__init__.py
src/connectors/wh/bigquery_base_connector.py
src/wht/mockPB.py
src/wht/pb.py
src/wht/rudderPB.py
train.py

refactor: extract out pb compile in a separate class

---

.gitignore
src/connectors/Connector.py
src/ml_core/preprocess_and_predict.py
src/ml_core/preprocess_and_train.py

fixed bug to process ignore features

---

.github/workflows/integration-test-redshift.yaml
.github/workflows/integration-test-snowflake.yaml
README.md
train.py

Reverting python version to 3.8.15

---

samples/py_native/models/inputs.yaml
samples/py_native/models/profiles.yaml
samples/py_native/pb_project.yaml
src/py_native/.gitignore
src/py_native/classifier/profiles_rudderstack_classifier/__init__.py
src/py_native/classifier/profiles_rudderstack_classifier/prediction.py
src/py_native/classifier/profiles_rudderstack_classifier/training.py
src/py_native/classifier/setup.py
src/py_native/requirements.txt

- Added a directory `src/py_native` which will host all the py native packages
- Created a `classifier` directory which contains `profiles_rudderstack_classifier` package. This package has two model types - `classifier_training` and `classifier_prediction` 
- Added a sample project for local testing of the py native models
> Fix [#1]()

feat: scaffold py native models

---

requirements.txt
scripts/simulate_pb_run.py
src/predictions/rudderstack_predictions/connectors/BigQueryConnector.py
src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
src/predictions/rudderstack_predictions/connectors/Connector.py
src/predictions/rudderstack_predictions/connectors/RedshiftConnector.py
src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
src/predictions/rudderstack_predictions/connectors/wh/bigquery_base_connector.py
src/predictions/rudderstack_predictions/connectors/wh/profiles_connector.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
src/predictions/rudderstack_predictions/train.py
src/predictions/rudderstack_predictions/utils/utils.py
src/predictions/rudderstack_predictions/wht/rudderPB.py
tests/integration/requirements.txt
tests/unit/utils_tests.py

modified:   requirements.txt
modified:   scripts/simulate_pb_run.py
modified:   src/predictions/rudderstack_predictions/connectors/BigQueryConnector.py
modified:   src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
modified:   src/predictions/rudderstack_predictions/connectors/Connector.py
modified:   src/predictions/rudderstack_predictions/connectors/RedshiftConnector.py
modified:   src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
modified:   src/predictions/rudderstack_predictions/connectors/wh/bigquery_base_connector.py
modified:   src/predictions/rudderstack_predictions/connectors/wh/profiles_connector.py
modified:   src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
modified: …

PRML-359: changes for bigquery train

---

predict.py
src/predictions/rudderstack_predictions/connectors/ConnectorFactory.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
src/predictions/rudderstack_predictions/train.py
tests/integration/requirements.txt
tests/integration/snowflake/classifier.py
tests/integration/snowflake/regressor.py

modified:   src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
modified:   src/predictions/rudderstack_predictions/train.py
modified:   tests/integration/requirements.txt
> Fix [#1]()

BigQueryConnector import correction

---

scripts/simulate_pb_run.py
src/predictions/rudderstack_predictions/connectors/BigQueryConnector.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py

modified:   scripts/simulate_pb_run.py
modified:   src/predictions/rudderstack_predictions/connectors/BigQueryConnector.py
modified:   src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
modified:   src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
> Fix [#1]()

PRML-360-changes-for-bigquery-predict

---

.gitignore

chore: add siteconfig file to gitignore

---

.gitignore
scripts/delete_snowflake_integration_test_stage.ipynb

modified:   .gitignore
new file:   scripts/delete_snowflake_integration_test_stage.ipynb
> Fix [#1]()

ipynb notebook to delete stages in integr. tests

---

scripts/simulate_pb_run.py
src/predictions/rudderstack_predictions/utils/utils.py
tests/unit/utils_tests.py

Checking for timezone info in the datetime string.

---

scripts/load_historic_data.ipynb

Added script on how to load historic materialised data

---

samples/application_project/models/profiles-ml.yaml
samples/predictions_dev_project/models/profiles-ml.yaml

Adding smart data generation configs to sample feature projects

---

src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
src/predictions/rudderstack_predictions/train.py
src/predictions/rudderstack_predictions/trainers/MLTrainer.py
src/predictions/rudderstack_predictions/utils/constants.py
src/predictions/rudderstack_predictions/utils/utils.py
src/predictions/rudderstack_predictions/wht/pythonWHT.py
src/predictions/rudderstack_predictions/wht/rudderPB.py

Standardising datetime to-and-fro conversions

---

samples/application_project/models/profiles-ml.yaml
samples/predictions_dev_project/models/profiles-ml.yaml

modified:   samples/application_project/models/profiles-ml.yaml
modified:   samples/predictions_dev_project/models/profiles-ml.yaml
> Fix [#1]()

indentation issue

---

predict.py
samples/py_native/models/inputs.yaml
samples/py_native/models/profiles.yaml
scripts/simulate_py_native.py
src/predictions/rudderstack_predictions/__init__.py
src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
src/predictions/rudderstack_predictions/predict.py
src/predictions/rudderstack_predictions/py_native/prediction.py
src/predictions/rudderstack_predictions/py_native/training.py
src/predictions/rudderstack_predictions/train.py
src/predictions/rudderstack_predictions/utils/constants.py
src/predictions/rudderstack_predictions/utils/utils.py
src/predictions/rudderstack_predictions/wht/pyNativeWHT.py
tests/integration/redshift/classifier.py
tests/integration/redshift/regressor.py
tests/integration/snowflake/classifier.py
tests/integration/snowflake/regressor.py
train.py

This PR implements the prediction pynative model
- Extracted out the common predict code so that it can be used by both python and pynative models
- Added 2 proxy functions in pyNativeWht
- Created common util code for getting path of model_configs.yaml file
> Fix [#1]()

feat: implement prediction pynative model recipe

---

src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
src/predictions/rudderstack_predictions/connectors/Connector.py
src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
src/predictions/rudderstack_predictions/train.py
src/predictions/rudderstack_predictions/wht/pyNativeWHT.py
src/predictions/rudderstack_predictions/wht/pythonWHT.py
src/predictions/rudderstack_predictions/wht/rudderPB.py

modified:   src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
modified:   src/predictions/rudderstack_predictions/connectors/Connector.py
modified:   src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
modified:   src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
modified:   src/predictions/rudderstack_predictions/train.py
modified:   src/predictions/rudderstack_predictions/wht/pyNativeWHT.py
modified:   src/predictions/rudderstack_predictions/wht/pythonWHT.py
modified:   src/predictions/rudderstack_predictions/wht/rudderPB.py
> Fix [#1]()

renaming feature_table_name to entity_var_table_name

---

src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
tests/unit/RedshiftConnector.py
tests/unit/SnowflakeConnector.py

modified error message for class imbalance check

---

requirements.txt

These packages have been deployed in prod
> Fix [#1]()

chore: enable BQ dependencies in requirements file

---

src/predictions/rudderstack_predictions/connectors/BigQueryConnector.py

Added numeric datatype to bigquery

---

Dockerfile
src/predictions/rudderstack_predictions/processors/K8sProcessor.py

Built the image with the latest classifier code
> Fix [#1]()

chore: update k8s processor image

---

src/predictions/rudderstack_predictions/processors/K8sProcessor.py

fix: update docker image to include #254 PR

---

predict.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
src/predictions/rudderstack_predictions/predict.py
src/predictions/rudderstack_predictions/processors/K8sProcessor.py
src/predictions/rudderstack_predictions/processors/LocalProcessor.py
src/predictions/rudderstack_predictions/processors/Processor.py
src/predictions/rudderstack_predictions/processors/SnowflakeProcessor.py
src/predictions/rudderstack_predictions/train.py
src/predictions/rudderstack_predictions/trainers/MLTrainer.py
src/predictions/rudderstack_predictions/trainers/TrainerFactory.py
src/predictions/rudderstack_predictions/utils/constants.py
tests/unit/MLTrainer.py
tests/unit/RedshiftConnector.py

refactor: create factory method for trainer

---

src/predictions/rudderstack_predictions/processors/K8sProcessor.py

chore: update profiles-classifier image to v0.2.3

---

src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py
src/predictions/rudderstack_predictions/processors/K8sProcessor.py

Bug introduced when resolving merge conflicts
> Fix [#1]()

fix: remove mode argument from download_directory function call

---

src/predictions/rudderstack_predictions/connectors/Connector.py
src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py
src/predictions/rudderstack_predictions/train.py

> Including ignore_features while fetching input_column_types.
> Fix [#1]()

Considering customer ignore_features

---

Dockerfile
src/predictions/rudderstack_predictions/processors/K8sProcessor.py

chore: update docker image to v0.3.0

---

src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py

Modified error messages in validate_label_distinct_value s in both SnowflakeConnector.py and CommonWarehouseConnector.py and added exception block in add_days_diff in CommonWarehouseConnector.py

Modified Error Messages and Added Exception Block 

---

src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py
src/predictions/rudderstack_predictions/connectors/Connector.py
src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py
src/predictions/rudderstack_predictions/trainers/MLTrainer.py
tests/unit/RedshiftConnector.py

Getting negative samples count from merged feature and label table

---

src/predictions/rudderstack_predictions/utils/utils.py

fix: output stdout as debug log when subprocess errors

---

src/predictions/rudderstack_predictions/wht/rudderPB.py

fix: retries for parsing json from stdout

---

src/predictions/rudderstack_predictions/__init__.py
src/predictions/rudderstack_predictions/py_native/llm.py

Implemented a basic structure for the new llm model
> Fix [#1]()

Implemented a basic structure for the new llm model

---

src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py

fix: remove extra session extra argument

---

samples/py_native/models/profiles.yaml
src/predictions/rudderstack_predictions/py_native/prediction.py
src/predictions/rudderstack_predictions/py_native/training.py
src/predictions/rudderstack_predictions/wht/pyNativeWHT.py

feat: get site config details for py native model from pywht

---

src/predictions/rudderstack_predictions/trainers/ClassificationTrainer.py
src/predictions/rudderstack_predictions/trainers/MLTrainer.py
src/predictions/rudderstack_predictions/trainers/RegressionTrainer.py
src/predictions/rudderstack_predictions/utils/utils.py

added fbeta score

---

samples/llm_model/models/inputs.yaml
samples/llm_model/models/profiles.yaml

Added the llm sample projects using Identifies table.
> Fix [#1]()

 Replaced the table from custom to Identifies

---

src/predictions/rudderstack_predictions/py_native/llm.py
tests/unit/llm.py

Added unit test for pynative llm model
> Fix [#1]()

 Added unit test for pynative llm model

---

src/predictions/version.py

chore: bump version to 0.1.0

---

.github/workflows/publish.yaml
.github/workflows/release.yaml

chore: add github action to publish mlcorelib

---

src/predictions/version.py

Reverts rudderlabs/rudderstack-profiles-classifier#310

Revert "chore: bump version to 0.1.0"

---

.github/workflows/release.yaml

fix: update prepare dist arrchves step of release GHA

---

.github/workflows/release.yaml

chore: add dist path in prepare dist archives step

---

.github/workflows/release.yaml

chore: update path in create release step

---

.github/workflows/publish.yaml

chore: update pattern in publish GHA

---

.github/workflows/release.yaml

chore: remove source distribution from release GHA

---

src/predictions/version.py

chore: bump version to v0.2.0

---

src/predictions/profiles_mlcorelib/connectors/CommonWarehouseConnector.py
src/predictions/profiles_mlcorelib/connectors/wh/redshift_base_connector.py
src/predictions/profiles_mlcorelib/processors/K8sProcessor.py

This PR reverts the changes in #298 and fixes a bug in the if check
> Fix [#1]()

revert: remove hardcoded local processor mode

---

src/predictions/profiles_mlcorelib/py_native/llm.py

Corrected the sql query in the pynative llm model
> Fix [#1]()

Corrected the sql query in the pynative llm model

---

.github/workflows/integration-test-bigquery.yaml
.github/workflows/integration-test-redshift.yaml
.github/workflows/integration-test-snowflake.yaml
.github/workflows/tests.yaml
samples/py_native/models/profiles.yaml
src/predictions/profiles_mlcorelib/py_native/training.py
src/predictions/profiles_mlcorelib/train.py
tests/integration/bigquery/pynative.py
tests/integration/snowflake/pynative.py
tests/integration/utils.py

chore: add bigquery pynative integration test

---

src/predictions/profiles_mlcorelib/processors/K8sProcessor.py

chore: update Docker image to v0.3.2

---

samples/llm_model/models/profiles.yaml
src/predictions/profiles_mlcorelib/py_native/llm.py
tests/unit/llm.py

> Adding support for eligible_users conditions in case of LLM. Ticket [link](https://linear.app/rudderstack/issue/PRML-617/add-eligible-users-flag-to-llm-pynative-models).
> Fix [#1]()

adding support for eligible_users flag in llm

---

src/predictions/profiles_mlcorelib/utils/utils.py

Removing the feature count from the copy since it is not guaranteed that chart will have those many features
> Fix [#1]()

chore: update copy of feature importance chart

---

scripts/quickstart_guide/Readme.md
scripts/quickstart_guide/requirements.txt
scripts/quickstart_guide/simulate_dataset.py

Added simulate dataset files

---

src/predictions/profiles_mlcorelib/utils/utils.py
tests/unit/utils_tests.py

fix: unable to extract seq no from quoted table name

---

src/predictions/version.py

chore: bump version to v0.3.0

---

.github/workflows/publish.yaml

chore: add support for publishing package in pypi dev

---

samples/py_native/pb_project.yaml

chore: remove version constraint from sample pynative project

---

src/predictions/profiles_mlcorelib/py_native/attribution_report.py

> ticket [link](https://linear.app/rudderstack/issue/PRML-744/modify-model-schema-spec-to-reflect-campaign-metadata-base-changes).
> Fix [#1]()

changing buildSpecSchema to support campaign_info

---

src/predictions/profiles_mlcorelib/py_native/attribution_report.py

2. added page views and distinct user coutns
> Fix [#1]()

1. modified model spec as per current prd

---

src/predictions/profiles_mlcorelib/connectors/CommonWarehouseConnector.py
src/predictions/profiles_mlcorelib/predict.py

chore: disable RudderStack mode for BQ and redshift

---

src/predictions/profiles_mlcorelib/wht/pythonWHT.py
tests/unit/pythonWHT.py

fix: find model refs of entity vars using pb show models

---

samples/py_native/models/profiles.yaml
src/predictions/profiles_mlcorelib/py_native/prediction.py

fix: move features field inside model_spec for prediction model

---

src/predictions/profiles_mlcorelib/py_native/prediction.py

feat: add output contract in prediction model

---

src/predictions/version.py

chore: bump version to v0.3.1

---

src/predictions/profiles_mlcorelib/py_native/attribution_report.py

Added campaign cost
> Fix [#1]()

Added support for index creation from campaign start/end dates

---

scripts/Generate_BigQuery_data_for_load_testing.ipynb

updating load testing script for bigquery

---

src/predictions/profiles_mlcorelib/py_native/training.py
tests/integration/bigquery/pynative.py
tests/integration/redshift/pynative.py
tests/integration/snowflake/pynative.py
tests/integration/utils.py

 fix: set default enable status for training model 

---

src/predictions/profiles_mlcorelib/py_native/prediction.py
src/predictions/profiles_mlcorelib/py_native/training.py

> inputs is a list of string in select sql format.
> Fix [#1]()

passing select sql in input

---

src/predictions/profiles_mlcorelib/py_native/attribution_report.py

Changed the sql query to add features
> Fix [#1]()

Changed the sql query to add features

---

samples/predictions_dev_project/models/localMacros.yaml
samples/predictions_dev_project/models/profiles.yaml
src/predictions/profiles_mlcorelib/connectors/Connector.py
src/predictions/profiles_mlcorelib/ml_core/preprocess_and_train.py
src/predictions/profiles_mlcorelib/train.py
src/predictions/profiles_mlcorelib/wht/pyNativeWHT.py
src/predictions/profiles_mlcorelib/wht/pythonWHT.py
tests/unit/RedshiftConnector.py
tests/unit/pythonWHT.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-712/disable-array-type-features-for-all-warehouses).
> Fix [#1]()

disabling arraytype_features

---

src/predictions/profiles_mlcorelib/py_native/attribution_report.py

Added support for pywht
> Fix [#1]()

Added support for pywht

---

.github/workflows/release.yaml

chore: skip version bump PR when rc tag is created

---

src/predictions/version.py

chore: bump version to v0.4.0

---

src/predictions/profiles_mlcorelib/py_native/attribution_report.py

Added a campaign_var_cte
> Fix [#1]()

Added a campaign_var_cte

---

src/predictions/version.py

chore: bump version to v0.4.1

---

src/predictions/profiles_mlcorelib/py_native/attribution_report.py

Reversed a single query
> Fix [#1]()

Reversed a single query

---

src/predictions/profiles_mlcorelib/wht/pyNativeWHT.py

Replaced the get method and tested the pipeline
> Fix [#1]()

Replaced the get method in pynativeWHT and tested the pipeline

---

requirements.txt
samples/predictions_dev_project/models/profiles.yaml
src/predictions/profiles_mlcorelib/config/model_configs.yaml
src/predictions/profiles_mlcorelib/connectors/BigQueryConnector.py
src/predictions/profiles_mlcorelib/connectors/CommonWarehouseConnector.py
src/predictions/profiles_mlcorelib/connectors/Connector.py
src/predictions/profiles_mlcorelib/connectors/RedshiftConnector.py
src/predictions/profiles_mlcorelib/connectors/SnowflakeConnector.py
src/predictions/profiles_mlcorelib/ml_core/preprocess_and_predict.py
src/predictions/profiles_mlcorelib/ml_core/preprocess_and_train.py
src/predictions/profiles_mlcorelib/train.py
src/predictions/profiles_mlcorelib/trainers/ClassificationTrainer.py
src/predictions/profiles_mlcorelib/trainers/MLTrainer.py
src/predictions/profiles_mlcorelib/trainers/RegressionTrainer.py
src/predictions/profiles_mlcorelib/trainers/TrainerFactory.py
src/predictions/profiles_mlcorelib/utils/constants.py
src/predictions/profiles_mlcorelib/utils/utils.py
src/predictions/setup.py
tests/integration/bigquery/classifier.py
tests/integration/bigquery/regressor.py
tests/integration/redshift/classifier.py
tests/integration/redshift/regressor.py
tests/integration/requirements.txt
tests/integration/snowflake/classifier.py
tests/integration/snowflake/regressor.py
tests/integration/utils.py
tests/unit/MLTrainer.py
tests/unit/RedshiftConnector.py
tests/unit/SnowflakeConnector.py

Duplicate of #350 
> Fix [#1]()

feat: integrate PyCaret

---

src/predictions/profiles_mlcorelib/py_native/attribution_report.py

Added metrics around time between first touch and conversion date using a CTE inside the selector_query.
> Fix [#1]()

Added metrics around time between first touch and conversion date using a CTE

---

samples/application_project/base_features/models/profiles-ml.yaml
samples/application_project/models/profiles-ml.yaml
samples/py_native/models/profiles.yaml
scripts/simulate_pb_run.py
src/predictions/profiles_mlcorelib/config/model_configs.yaml
src/predictions/profiles_mlcorelib/connectors/CommonWarehouseConnector.py
src/predictions/profiles_mlcorelib/connectors/Connector.py
src/predictions/profiles_mlcorelib/connectors/SnowflakeConnector.py
src/predictions/profiles_mlcorelib/ml_core/preprocess_and_predict.py
src/predictions/profiles_mlcorelib/ml_core/preprocess_and_train.py
src/predictions/profiles_mlcorelib/predict.py
src/predictions/profiles_mlcorelib/processors/K8sProcessor.py
src/predictions/profiles_mlcorelib/processors/LocalProcessor.py
src/predictions/profiles_mlcorelib/processors/Processor.py
src/predictions/profiles_mlcorelib/processors/SnowflakeProcessor.py
src/predictions/profiles_mlcorelib/train.py
src/predictions/profiles_mlcorelib/trainers/RegressionTrainer.py
src/predictions/profiles_mlcorelib/wht/pyNativeWHT.py
src/predictions/profiles_mlcorelib/wht/pythonWHT.py
tests/integration/bigquery/classifier.py
tests/integration/bigquery/regressor.py
tests/integration/redshift/classifier.py
tests/integration/redshift/regressor.py
tests/integration/snowflake/classifier.py
tests/integration/snowflake/regressor.py
tests/integration/utils.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-778/yaml-cleanup).
> Fix [#1]()

Changing yaml structure

---

src/predictions/version.py

chore: bump version to v0.4.2

---

samples/py_native/models/profiles.yaml
src/predictions/profiles_mlcorelib/py_native/training.py

fix: add yaml validations in training model

---

samples/py_native/models/profiles.yaml
src/predictions/profiles_mlcorelib/wht/pyNativeWHT.py

Reverts rudderlabs/rudderstack-profiles-classifier#410

Revert "Sample code changes for include support for path-reference format in label_column"

---

src/predictions/profiles_mlcorelib/trainers/ClassificationTrainer.py
src/predictions/profiles_mlcorelib/trainers/RegressionTrainer.py
tests/unit/MLTrainer.py

This task type will be used by the UI to determine the relevant metrics
> Fix [#1]()

feat: add task type in training summary

---

.github/workflows/tests.yaml
src/predictions/profiles_mlcorelib/wht/pyNativeWHT.py
src/predictions/profiles_mlcorelib/wht/pythonWHT.py
tests/unit/llm.py

chore: bump black version to 24.8.0

---

samples/py_native/models/profiles.yaml
src/predictions/profiles_mlcorelib/__init__.py
src/predictions/profiles_mlcorelib/py_native/prediction.py
src/predictions/profiles_mlcorelib/py_native/propensity.py
src/predictions/profiles_mlcorelib/py_native/training.py
src/predictions/setup.py
tests/integration/utils.py

feat: propensity model as a wrapper for training and prediction models

---

src/predictions/profiles_mlcorelib/ml_core/preprocess_and_predict.py
src/predictions/profiles_mlcorelib/ml_core/preprocess_and_train.py
src/predictions/profiles_mlcorelib/utils/utils.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-861/check-if-feature-table-column-string-type-in-output-json-is-required).
> Fix [#1]()

changing feature_table_col_type structure

---

src/predictions/profiles_mlcorelib/trainers/MLTrainer.py
src/predictions/profiles_mlcorelib/wht/pythonWHT.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-852/feature-causing-multiple-runs-need-more-logging-for-better-visibility).
> Fix [#1]()

adding minor logs

---

src/predictions/profiles_mlcorelib/py_native/attribution_report.py

…campaign_date
Added and renamed columns in the selector_Sql to get Latest_date and Campaign_Date
> Fix [#1]()

Added and renamed columns in the selector_Sql to get Latest_date and Campaign_Date

---

src/predictions/version.py

chore: bump version to v0.5.0

---

src/predictions/profiles_mlcorelib/train.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-858/remove-references-to-output-profiles-ml-model-in-config).
> Fix [#1]()

detaching argument from customer config

---

samples/py_native/models/profiles.yaml

> Adding new_materialisation_info to customer configs for pynative model.
> Fix [#1]()

adding additional configs to customer config

---

src/predictions/version.py

chore: bump version to v0.5.1

---

src/predictions/profiles_mlcorelib/trainers/ClassificationTrainer.py

> correcting plots so that it takes positive class probabilities as prediction probabilities. 
> Fix [#1]()

correcting pr-auc, roc-auc plots generation

---

samples/attribution_project/models/profiles.yaml
src/predictions/profiles_mlcorelib/py_native/attribution_report.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-908/add-where-clause-to-user-journeys).
> Fix [#1]()

adding support for where clause in user_journey

---

src/predictions/version.py

chore: bump version to v0.5.2

---

src/predictions/version.py

chore: bump version to v0.5.3

---

src/predictions/profiles_mlcorelib/py_native/attribution_report.py
tests/unit/attribution/attribution.py
tests/unit/attribution/output.sql
tests/unit/mocks.py
tests/unit/pyNativeWHT.py

test: add unit tests for attribution model

---

.github/workflows/integration-test-bigquery.yaml
.github/workflows/integration-test-redshift.yaml
.github/workflows/integration-test-snowflake.yaml
src/predictions/profiles_mlcorelib/py_native/llm.py

chore: skip running python model tests if propensity model hasn't changed

---

.github/workflows/tests.yaml
samples/attribution_project/pb_project.yaml
tests/integration/attribution/attribution.py

test: add integration test for attribution project

---

samples/py_native/models/profiles.yaml
src/predictions/profiles_mlcorelib/py_native/training.py
tests/unit/training.py

fix: training model fails if label column is not part of inputs

---

src/predictions/version.py

chore: bump version to v0.5.4

---

src/predictions/profiles_mlcorelib/__init__.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/debugger.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/yamlReport.py

This PR adds a new pynative model type `id_stitcher_debugger` in `profiles_mlcorelib` repo. Currently it implements YamlReport. More reports will be added in later PRs
> Fix [#1]()

feat: add id stitcher debugger model type

---

.github/workflows/integration-test-bigquery.yaml
.github/workflows/integration-test-redshift.yaml
.github/workflows/integration-test-snowflake.yaml
.github/workflows/tests.yaml

chore: update file filters for propensity model tests

---

src/predictions/profiles_mlcorelib/py_native/id_stitcher/debugger.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/yaml_report.py

feat: add table report in id stitcher debugger

---

src/predictions/profiles_mlcorelib/py_native/id_stitcher/cluster_report.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/debugger.py
src/predictions/setup.py

feat: add cluster report in id stitcher debugger

---

src/predictions/version.py

chore: bump version to v0.5.5

---

src/predictions/profiles_mlcorelib/__init__.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/cluster_report.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/config.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/llm_report.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/yaml_report.py

- Added `llm_report` which makes call to LLM service
- Fixed bug in `table_report` and `yaml_report`
- Updated the pywht interface to get `id` fields as methods instead of dictionary keys
- Renamed `debug` to `audit`
> Fix [#1]()

feat: add llm report in audit id stitcher model

---

src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py

> spelling mistake for mappings table.
> Fix [#1]()

fix: audit model sql query failing because of incorrect table name

---

src/predictions/version.py

chore: bump version to v0.5.6

---

.github/workflows/tests.yaml
src/predictions/profiles_mlcorelib/py_native/training.py

Currently when using python3.11, the training model fails while running. This PR adds validations in the compile step.
> Fix [#1]()

fix: error in installing required packages in Snowpark with python version 3.11

---

src/predictions/version.py

chore: bump version to v0.5.7

---

samples/py_native/models/profiles.yaml
src/predictions/profiles_mlcorelib/wht/pyNativeWHT.py
tests/integration/utils.py
tests/unit/mocks.py

chore: add cohort label column in sample project

---

src/predictions/setup.py

feat: allow installing mlcorelib for python 3.12

---

src/predictions/version.py

chore: bump version to v0.5.8

---

src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-955/1-add-drews-feedback-to-id-stitcher-analysis-tool).
> Fix [#1]()

adding query for highest count of other ids

---

.github/workflows/python-version.yaml
src/predictions/setup.py

fix: unable to install mlcorelib for python < 3.10

---

src/predictions/profiles_mlcorelib/py_native/id_stitcher/cluster_report.py
src/predictions/setup.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-956/2-drews-feedback-on-id-stitcher-analysis-visualiser-part).
> Fix [#1]()

adding visualizer

---

src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/llm_report.py
src/predictions/setup.py

feat: prompt user for access token if not present

---

.github/workflows/tests.yaml

test: snowflake propensity integration test in python 3.9

---

src/predictions/version.py

chore: bump version to v0.5.9

---

samples/py_native/pb_project.yaml

changing test path

---

src/predictions/profiles_mlcorelib/py_native/id_stitcher/config.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/llm_report.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/prompts.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1000/add-llm-analysis-of-static-report).
> Fix [#1]()

supporting static report for id stitcher

---

src/predictions/version.py

chore: bump version to v0.6.0

---

src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/database_manager.py
src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/tutorial.py

- Include migrate_on_load in pb run & pb compile
- Fix pongo template for upload sample data
Resolves PRML-1007

fix: upload data and migrate on load

---

src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/tutorial.py

Minor bug fixes identified during local run

---

.github/workflows/release.yaml
src/predictions/profiles_mlcorelib/utils/constants.py
src/predictions/profiles_mlcorelib/utils/tracking.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1034/move-analytics-config-to-environment-variables-for-app-publishing).
> Fix [#1]()

moving tracking constants to github vars

---

src/predictions/profiles_mlcorelib/py_native/attribution_report.py
src/predictions/profiles_mlcorelib/py_native/propensity.py
src/predictions/profiles_mlcorelib/wht/pyNativeWHT.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-997/fixes-after-019-release).
> Fix [#1]()

changes after 0.19 release

---

src/predictions/profiles_mlcorelib/__init__.py

> Revert registering tutorial model

chore: revert registering tutorial model

---

src/predictions/profiles_mlcorelib/ml_core/preprocess_and_train.py
src/predictions/profiles_mlcorelib/processors/K8sProcessor.py
src/predictions/profiles_mlcorelib/processors/LocalProcessor.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1043/propensity-model-fix-bug-in-validation-check-for-local-processor-mode).
> Fix [#1]()

script-2 missing connector feature_table_name

---

.github/workflows/release.yaml

fix: vars in release yaml

---

.github/workflows/release.yaml

revert: tracking changes in release GHA

---

src/predictions/version.py

chore: bump version to 0.6.2

---

src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py
src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/model.py
src/predictions/profiles_mlcorelib/py_native/propensity.py

> wht 0.20.0 will support output_type `none` & `shell`
Respective wht [PR](https://github.com/rudderlabs/wht/pull/1869)
Resolves PRML-992

fix: output_type for tutorial

---

src/predictions/profiles_mlcorelib/train.py

> Remove latest_entity_var_table as it's no longer being used
> Fix [#1]()

fix: latest entity var table from train

---

tests/unit/audit.py
tests/unit/mocks.py

> Ticket [link](https://linear.app/rudderstack/issue/PRML-1018/add-unit-tests-and-integration-tests).
> Fix [#1]()

adding unittest for audit

---

src/predictions/profiles_mlcorelib/py_native/id_stitcher/llm_report.py

temp fix for RS port

---

.github/workflows/tests.yaml

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1047/turn-on-bigquery-integration-tests-again).
> Fix [#1]()

enabling bigquery tests

---

src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/tutorial.py
src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/yaml_generator.py

> Skip Manual step to update yaml (removing shopify_store_id), incase of fast model

chore: skip manual updation in fast model

---

src/predictions/profiles_mlcorelib/__init__.py

> Uncomment registraton
> Fix [#1]()

chore: register tutorial model

---

.github/workflows/tests.yaml
samples/integration_test_project/models/inputs.yaml
samples/integration_test_project/models/localMacros.yaml
samples/integration_test_project/models/macros.yaml
samples/integration_test_project/models/profiles.yaml
samples/integration_test_project/models/sql_models.yaml
samples/integration_test_project/pb_project.yaml
samples/py_native/pb_project.yaml
tests/integration/audit/audit.py
tests/integration/sample_project/pb_project.yaml

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1036/add-ci-tests-for-pb-audit-pynative-model).
> Fix [#1]()

adding audit integration test

---

samples/integration_test_project/README.md

updating readme

---

src/predictions/profiles_mlcorelib/ml_core/preprocess_and_predict.py
src/predictions/profiles_mlcorelib/utils/utils.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1062/ignore-features-from-high-cardinality-causing-issue-in-predict).
> Fix [#1]()

considering only features that exist

---

requirements.txt
src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/database_manager.py
src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/model.py
src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/tutorial.py
tests/integration/tutorial/tutorial.py

Using pexpect to give input based on checking the terminal output and deciding what it expects
Note - This approach should work for audit too
- Explore other ways to test
- Add CI config in .github to run test

chore: tutorial integration test

---

src/predictions/profiles_mlcorelib/connectors/BigQueryConnector.py
src/predictions/setup.py

> Dailycaller issue on fetching registry table from batches.
> Fix [#1]()

pulling wh table batches in BQ

---

src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1089/add-consolidation-rate-metric-calculation-to-the-report).
> Fix [#1]()

adding consolidation rate to report

---

src/predictions/profiles_mlcorelib/py_native/id_stitcher/cluster_report.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1082/rename-degree-to-noof-connections-in-the-html-view).
> Fix [#1]()

renaming in html file

---

.github/workflows/tests.yaml
src/predictions/profiles_mlcorelib/py_native/propensity.py

Chore.remove print statements

---

src/predictions/version.py

chore: bump version to v0.7.0

---

src/predictions/profiles_mlcorelib/predict.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py
src/predictions/profiles_mlcorelib/py_native/propensity.py
src/predictions/profiles_mlcorelib/train.py
src/predictions/profiles_mlcorelib/utils/utils.py
src/predictions/profiles_mlcorelib/wht/pyNativeWHT.py
src/predictions/setup.py

Added pb 0.20.0 related changes back, with a constraint in setup to profiles>=0.20.0
This will create a new release 0.7.2, so anyone on latest pb will get this. And new releases will be built on top of this.
So an overview:
* 0.7.0 - Buggy if anyone has pinned pb = 0.19.x and mlcorelib==0.7.0
* 0.7.1 - If anyone has pinned pb = 0.19.x and no pinning on mlcorelib
* 0.7.2 - Default for latest  pb (0.20.x)
> Fix [#1]()

Added pb 0.20.0 changes back

---

src/predictions/version.py

chore: bump version to v0.7.2

---

src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/model.py
src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/tutorial.py

> Ticket [link](https://linear.app/rudderstack/issue/PRML-1103/add-tracking-to-the-tutorial-model-start-and-end).
> Fix [#1]()

add tracking to tutorials model

---

samples/py_native/models/profiles.yaml
src/predictions/profiles_mlcorelib/utils/constants.py
src/predictions/profiles_mlcorelib/utils/utils.py
tests/integration/utils.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1105/feature-importance-chart-not-being-generated-for-sf).
> Fix [#1]()

feature_importance chart issue

---

.github/workflows/tests.yaml
src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py
src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py
tests/unit/attribution/attribution.py
tests/unit/attribution/output.sql
tests/unit/audit_helper/test_table_report.py
tests/unit/mocks.py

Added a check in audit id stitcher to assert it is not being run on incremental model
Added unittest for new changes
Fixed unittests not being triggered in sub-directories Minor refactoring in tablereport, where warehouse specific subqueries were earlier being checked in if-else conditions. moved that to a map for easier organisation
> Fix [#1]()

Ensure audit is run on batch id stitcher only

---

samples/attribution_project/models/attribution.yaml
samples/attribution_project/models/sql_models.yaml
src/predictions/profiles_mlcorelib/py_native/attribution_report.py
tests/unit/mocks.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1050/support-sql-models-with-an-existing-main-id-column).
> Fix [#1]()

Support sql models with an existing main_id column

---

src/predictions/version.py

chore: bump version to v0.7.3

---

src/predictions/profiles_mlcorelib/connectors/CommonWarehouseConnector.py
src/predictions/profiles_mlcorelib/ml_core/preprocess_and_predict.py

> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1108/do-batch-predictions-to-support-large-datasets-in-bigquery-and).
- Loading prediction data in batches in case of RS and BQ.
- inserting further batches in warehouse.
- adding percentile score query.

batch prediction in case of redshift and bigquery

---

src/predictions/profiles_mlcorelib/utils/constants.py
src/predictions/setup.py

> Updating shap module version to 0.46.0 in train stored procedure.
> Fix [#1]()

updating shap version in sproc
