src/connectors/Connector.py, tests/unit/RedshiftConnector.py
=> fixed log message when historic input tables are not matching

src/predictions/rudderstack_predictions/connectors/wh/bigquery_base_connector.py, src/predictions/rudderstack_predictions/connectors/wh/redshift_base_connector.py
> warehouse connector's `write_to_table()` was also creating the table if it doesn't exist. But this shouldn't happen in ideal case.
> It's being used to write metrics dataframe and final predictions dataframe.
> Metric table name is also passed to train script from profiles. So, That's also unique and it's existing case is already considered.
> Removal of writing feature_importance dataframe to warehouse has already been handled in PR (#268 ).
> Fix [#1]()
=> raise exc. while writing if table is not present

src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py, src/predictions/rudderstack_predictions/train.py, src/predictions/rudderstack_predictions/utils/utils.py
> In addition to feature_importance chart, we were also writing feature_importance table to warehouse. But this was never being used further, neither in code nor in UI. Written table destination is also same which can result in unnecessary conflicts if multiple projects run in same schema.
> Fix [#1]()
=> removing unnecesaary table uploads to warehouse

src/predictions/rudderstack_predictions/connectors/BigQueryConnector.py, src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py, src/predictions/rudderstack_predictions/connectors/Connector.py, src/predictions/rudderstack_predictions/connectors/ConnectorFactory.py, src/predictions/rudderstack_predictions/connectors/RedshiftConnector.py, src/predictions/rudderstack_predictions/connectors/SnowflakeConnector.py, src/predictions/rudderstack_predictions/ml_core/preprocess_and_predict.py, src/predictions/rudderstack_predictions/ml_core/preprocess_and_train.py, src/predictions/rudderstack_predictions/predict.py, src/predictions/rudderstack_predictions/processors/Processor.py, src/predictions/rudderstack_predictions/processors/ProcessorFactory.py, src/predictions/rudderstack_predictions/processors/SnowflakeProcessor.py, src/predictions/rudderstack_predictions/train.py, src/predictions/rudderstack_predictions/trainers/MLTrainer.py, src/predictions/rudderstack_predictions/trainers/TrainerFactory.py, src/predictions/rudderstack_predictions/utils/utils.py, src/predictions/rudderstack_predictions/wht/mockPB.py, src/predictions/rudderstack_predictions/wht/pyNativeWHT.py, src/predictions/rudderstack_predictions/wht/pythonWHT.py, tests/integration/bigquery/classifier.py, tests/integration/bigquery/regressor.py, tests/integration/redshift/classifier.py, tests/integration/redshift/regressor.py, tests/integration/snowflake/classifier.py, tests/integration/snowflake/regressor.py, tests/integration/utils.py, tests/unit/RedshiftConnector.py, tests/unit/SnowflakeConnector.py, tests/unit/pyNativeWHT.py, tests/unit/pythonWHT.py
- `Connector` class is now computing `self.session` in its `init` method
- Removed `session` argument from all the connector methods except for those which are called by Snowpark. Now `self.session` is being used. Had to do some hacky stuff to make it work for creating a `sproc`
- Extracted out common integration test to `utils` file
https://linear.app/rudderstack/issue/PRML-516/code-refactoring-make-session-object-a-member-of-connector-class
> Fix [#1]()
=> refactor: move session object inside connector class

src/predictions/rudderstack_predictions/trainers/MLTrainer.py, src/predictions/rudderstack_predictions/utils/utils.py, src/predictions/rudderstack_predictions/wht/pythonWHT.py, tests/unit/RedshiftConnector.py, tests/unit/pythonWHT.py
=> Checking materialisations before running 'pb run'

src/predictions/rudderstack_predictions/connectors/CommonWarehouseConnector.py, src/predictions/rudderstack_predictions/connectors/wh/redshift_base_connector.py
ML model is currently broken in the UI. So changing the k8s mode to local mode now that we are using a separate pod. With this change, Redshift writes won't happen via S3. 
> Fix [#1]()
=> fix: use local mode instead of k8s mode for non-Snowflake warehouses

src/predictions/setup.py, src/predictions/version.py
Checking dist/profiles_mlcorelib-0.1.0-py3-none-any.whl: FAILED
ERROR    `long_description` has syntax errors in markup and would not be        
rendered on PyPI.                                                      
No content rendered from RST source.                                   
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
Checking dist/profiles_mlcorelib-0.1.0.tar.gz: PASSED with warnings
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.   
WARNING  `long_description` missing.  
> Fix [#1]()
=> chore: add long_description_content_type to fix publish error

src/predictions/profiles_mlcorelib/py_native/llm.py
Added caching functionality:
Made changes to the SQL Query. 
1. First we are selecting a distinct attribute values, on which snowflake cortex will be run.
2. Ones the output is received from the cortex, it is mapped again to the original table.
3. In this way the number of api hits made to the LLM model is reduced by using only distinct attribute values.
> Fix [#1]()
=> Added caching functionality

src/predictions/profiles_mlcorelib/py_native/llm.py
> in pb version>=0.13.0, name of prepare() has been changed to register_dependencies().
> Fix [#1]()
=> correcting fn name

scripts/simulate_pb_run.py, src/predictions/profiles_mlcorelib/connectors/CommonWarehouseConnector.py, src/predictions/profiles_mlcorelib/connectors/ConnectorFactory.py, src/predictions/profiles_mlcorelib/connectors/SnowflakeConnector.py, src/predictions/profiles_mlcorelib/connectors/wh/bigquery_base_connector.py, src/predictions/profiles_mlcorelib/connectors/wh/redshift_base_connector.py, src/predictions/profiles_mlcorelib/ml_core/preprocess_and_predict.py, src/predictions/profiles_mlcorelib/ml_core/preprocess_and_train.py, src/predictions/profiles_mlcorelib/predict.py, src/predictions/profiles_mlcorelib/processors/K8sProcessor.py, src/predictions/profiles_mlcorelib/processors/LocalProcessor.py, src/predictions/profiles_mlcorelib/py_native/prediction.py, src/predictions/profiles_mlcorelib/py_native/training.py, src/predictions/profiles_mlcorelib/train.py, src/predictions/profiles_mlcorelib/trainers/MLTrainer.py, src/predictions/profiles_mlcorelib/utils/S3Utils.py, src/predictions/profiles_mlcorelib/utils/logger.py, src/predictions/profiles_mlcorelib/utils/utils.py, src/predictions/profiles_mlcorelib/wht/pythonWHT.py, src/predictions/profiles_mlcorelib/wht/rudderPB.py
The logger which is being used in the predictions code doesn't work in the pynative flow since n python subprocess gets created. To make it work instead of getting the default logger at import time, now the code is getting the value at run time using the `.get()` method
- The logger class has a `set_logger` method which is being used by pynative training and prediction classes so that the code can start using the pynative logger
- Since the pynative logger doesn't have a `warning` method and `warn` method in python logger is deprecated. So replaced `warning` with `error` call
- Pynative logger can't be imported in snowflake stored procedure so using print statement there
> Fix [#1]()
=>  feat: integrate py native logger with predictions code 

src/predictions/profiles_mlcorelib/utils/utils.py, src/predictions/profiles_mlcorelib/wht/pythonWHT.py, tests/unit/utils_tests.py
=> fix: unable to split material name for quoted input

src/predictions/setup.py
0.14.0 - Pywht fix for prediction model able to access Training output
0.14.1 - wht fix for certain BQ projects not working
> Fix [#1]()
=> chore: make pb 0.14.1 the min version for 0.3.0 release

src/predictions/profiles_mlcorelib/connectors/wh/bigquery_base_connector.py
> Appending values on training metrics. Ticket [link](https://linear.app/rudderstack/issue/PRML-590/bug-training-metrics-v4-table-getting-replaced-in-bigquery).
> Fix [#1]()
=> appending values on training_metrics

src/predictions/profiles_mlcorelib/py_native/training.py
This PR adds support for skipping training model if it finds a valid training file from previous run. If found, it copies the directory to the current output folder so that the prediction model can use it without worrying about whether training was skipped or not. A dummy table is also created in the warehouse since pb requires it.
To implement this, added support for 2 new fields in the yaml - `training_file_lookup_path` and `validity_time`
`validity_time` - Specifies how old training outputs can be used
`training_file_lookup_path` - The directory in which model should search for the training files
> Fix [#1]()
=> feat: skip training if valid file is present from previous runs

src/predictions/profiles_mlcorelib/py_native/training.py, src/predictions/profiles_mlcorelib/utils/S3Utils.py
When running the project from UI, the artefacts get uploaded on S3. Updated the training check method to check for files in S3 if the details are provided in site config
> Fix [#1]()
=> feat: skip training in UI if valid file is present from previous runs

src/predictions/profiles_mlcorelib/config/model_configs.yaml, src/predictions/profiles_mlcorelib/train.py, src/predictions/profiles_mlcorelib/trainers/MLTrainer.py, src/predictions/profiles_mlcorelib/utils/utils.py, src/predictions/profiles_mlcorelib/wht/pyNativeWHT.py, src/predictions/profiles_mlcorelib/wht/pythonWHT.py, tests/unit/MLTrainer.py, tests/unit/pyNativeWHT.py
> Ticket [link](https://linear.app/rudderstack/issue/PRML-796/remove-train-start-dt-and-train-end-dt-support-in-inputs).
> Fix [#1]()
=> removing start_date and end_date from configs

src/predictions/profiles_mlcorelib/connectors/SnowflakeConnector.py
> right now, both the tables have same columns, so, it creates ambiguous results after join.
> Fix [#1]()
=> only joining while having entity_column in table

src/predictions/profiles_mlcorelib/py_native/training.py, src/predictions/setup.py
In pb 0.16.0, the key was [renamed](https://github.com/rudderlabs/wht/pull/1569) from `enable_status` to `requested_enable_status`. This PR makes the same change in the training model for the logic to keep working in pb >= 0.16.0
> Fix [#1]()
=> fix: update the enable status key as per pb 0.16.0 changes

samples/py_native/models/profiles.yaml, src/predictions/profiles_mlcorelib/py_native/training.py
This field won't work in CI since `training_file_lookup_path` is missing and outputs are not shared across runs.
> Fix [#1]()
=> chore: add training validity in sample project

src/predictions/setup.py
`profiles_mlcorelib` doesn't support python3.12 because of `snowflake-snowpark-python` 
> Fix [#1]()
=> fix: add python version constraint

requirements.txt, src/predictions/profiles_mlcorelib/connectors/CommonWarehouseConnector.py, src/predictions/profiles_mlcorelib/connectors/Connector.py, src/predictions/profiles_mlcorelib/connectors/SnowflakeConnector.py, src/predictions/profiles_mlcorelib/ml_core/preprocess_and_predict.py, tests/unit/SnowflakeConnector.py
> Ticket [link](https://linear.app/rudderstack/issue/PRML-860/fetch-data-types-from-var-table-during-predict-time-in-snowflake).
> Fix [#1]()
=> fetching type_hints from table directly

src/predictions/profiles_mlcorelib/trainers/ClassificationTrainer.py, src/predictions/profiles_mlcorelib/trainers/RegressionTrainer.py, tests/unit/MLTrainer.py
> Ticket [Link](https://linear.app/rudderstack/issue/PRML-484/change-the-output-metrics-structure-on-ui-to-support-pycaret-migration).
> Fix [#1]()
=> passing model name in training_summary json

samples/py_native/models/profiles.yaml, src/predictions/profiles_mlcorelib/py_native/propensity.py
- Moved `training_params`, `type`, `training_validity` and `training_file_lookup_path` under `training` 
- Moved `prediction_eligible_users` under `prediction`
> Fix [#1]()
=> fix: move all training related keys under training in propensity YAML

src/predictions/profiles_mlcorelib/config/model_configs.yaml
Removed the 2 fields `label_column` and `prediction_horizon_days` since they are supposed to be provided by the customer.
> Fix [#1]()
=> fix: remove mandatory fields from the default config

samples/attribution_project/models/profiles.yaml, src/predictions/profiles_mlcorelib/py_native/attribution_report.py
Till now we were asking the user to pass the `timestamp` field of the touchpoint models because the attribution model had no way to access the timestamp of the given model. This PR simplifies the YAML by removing the duplication due to the `timestamp` field. Instead the value is now being derived from the `time_filtering_column`
This is a BREAKING CHANGE since the model no more allows passing in a `timestamp` field
> Fix [#1]()
=> refactor: infer touchpoint timestamp using wht internal methods

src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> Ticket [link](https://linear.app/rudderstack/issue/PRML-911/datediff-should-not-raise-errors-in-case-of-mismatched-data-types).
> Fix [#1]()
=> selecting non-null, non-empty converted_date

.github/workflows/tests.yaml
=> chore: run propensity pynative tests only when model is updated

src/predictions/profiles_mlcorelib/py_native/prediction.py, src/predictions/profiles_mlcorelib/py_native/propensity.py
**BUG** - Feature view expects all the feature-models to have ids defined. But in the case of prediction model, the ids were missing
> Fix [#1]()
=> fix: prediction model is causing error in feature view

src/predictions/profiles_mlcorelib/connectors/SnowflakeConnector.py, src/predictions/profiles_mlcorelib/utils/constants.py, src/predictions/setup.py, tests/unit/pythonWHT.py
Current repo should support non encrypted p8 file too, but pywht needs a fix in sending that
> Fix [#1]()
=> Added support for encrypted key-pair authentication on snowflake

src/predictions/profiles_mlcorelib/py_native/propensity.py
**BUG** `folder_ref` method returns `packages/<package_name>/models` which throws error when trying to deRef training model `packages/<package_name>/models/training_model` from the prediction model.
**FIX** - Use a different method which returns ref as `models` without any package path
> Fix [#1]()
=> fix: propensity models in package project not working

src/predictions/profiles_mlcorelib/py_native/propensity.py
=> fix: additional fields in prediction output columns is not throwing error

src/predictions/profiles_mlcorelib/py_native/attribution_report.py
- Tested the attribution model by replacing `inputs/rsMarketingPages` with `rs_marketing_pages_sql`
- Added a new validation for timestamp column
```
- name: rs_marketing_pages_sql
model_type: sql_template
model_spec:
single_sql: "select CAMPAIGN_PROFILE_ID, USER_MAIN_ID, ANONYMOUS_ID, UTM_CAMPAIGN, TIMESTAMP from MATERIAL_RSMARKETINGPAGES_VAR_TABLE_B5F7FCDD_1000"
occurred_at_col: TIMESTAMP
ids:
- entity: user
select: user_main_id
type: rudder_id
- entity: campaign
select: campaign_profile_id
type: rudder_id
```
> Fix [#1]()
=> fix: attribution model error when entity main id columns are present as model ids

src/predictions/profiles_mlcorelib/connectors/CommonWarehouseConnector.py, src/predictions/profiles_mlcorelib/connectors/Connector.py, src/predictions/profiles_mlcorelib/connectors/SnowflakeConnector.py, src/predictions/profiles_mlcorelib/ml_core/preprocess_and_predict.py, src/predictions/profiles_mlcorelib/predict.py, src/predictions/profiles_mlcorelib/processors/K8sProcessor.py, src/predictions/profiles_mlcorelib/processors/LocalProcessor.py, src/predictions/profiles_mlcorelib/processors/Processor.py, src/predictions/profiles_mlcorelib/processors/SnowflakeProcessor.py, src/predictions/profiles_mlcorelib/wht/pyNativeWHT.py, src/predictions/profiles_mlcorelib/wht/pythonWHT.py
- We had a check `model_type='python_model'` when fetching the past table. This wouldn't work for propensity model. So removed the check
- Checking for `model_name` is not correct since it is possible for multiple projects with the same model name to run in the same schema. So replaced it with `model_hash` check. 
> Fix [#1]()
=> fix: fetching past predictions table not working in propensity model

src/predictions/profiles_mlcorelib/py_native/attribution_report.py, src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py, src/predictions/profiles_mlcorelib/py_native/id_stitcher/consent_manager.py, src/predictions/profiles_mlcorelib/py_native/id_stitcher/llm_report.py
Also added two other minor changes:
1. when the selected id stitcher model is not a valid selection (ex: an accidental enter would try to find an empty string in id stitcher model names), it prompts again for a valid selection - has a retry limit of 5
2. missed a review comment in a previous pr disabling a log. added that
```
You can explore specific clusters by entering an ID to see how the other ids are all connected and the cluster is formed.
The ID can be either the main ID or any other ID type.
Enter an ID to visualize (or 'skip' to skip this step): 
skip
Exiting interactive mode.
This process includes LLM-based analysis which may send some of your text data to LLM providers Anthropic and OpenAI as part of the API calls. 
Would you like to proceed? This choice will be rememberd for …
```
=> Added consent management for llm usage

src/predictions/MANIFEST.in, src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/file_generator.py, src/predictions/profiles_mlcorelib/py_native/profiles_tutorial/tutorial.py, src/predictions/setup.py
- Fix: include sample zip
- Fix: assumption that the python process will run from project dir
Resolves PRML-1007
=> fix: assumption that py process runs in project dir

src/predictions/profiles_mlcorelib/py_native/id_stitcher/audit.py, src/predictions/profiles_mlcorelib/py_native/warehouse.py
- `wht_ctx.client` is `None` when `register_dependencies` is called with `null_ctx` resulting in `Exception`
- `table_report.get_table_names` exception when material registry query returns empty result
- Skipping run in case of `null_ctx`
- No need to store run_completed on self
- refactored and improved variable names
- Refactored to get rid of type and lint erros
- added a debug log to get stack trace incase of exception, this can be controlled by env/log config file
- Added check to skip `result.columns.str.upper()` incase result is empty
Resolves PRML-1040
=> fix: audit ids client not found exception

src/predictions/setup.py
Snowpark 1.26.0 introduced a new method to get active session and that caused a regression in our prediction step in snowflake.
Limiting snowpark max version to address the issue. 
> Fix [#1]()
=> Limited snowpark max version to below 1.26.0

src/predictions/profiles_mlcorelib/py_native/id_stitcher/cluster_report.py
> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1039/id-types-colors-should-be-static-across-graphs-in-a-single-run).
> Fix [#1]()
=> making node colors static across clusters

src/predictions/profiles_mlcorelib/connectors/BigQueryConnector.py, src/predictions/profiles_mlcorelib/connectors/CommonWarehouseConnector.py, src/predictions/profiles_mlcorelib/connectors/Connector.py, src/predictions/profiles_mlcorelib/connectors/RedshiftConnector.py, src/predictions/profiles_mlcorelib/connectors/SnowflakeConnector.py
> Ticket [link](https://linear.app/rudderstack/issue/PRML-1055/get-rid-of-get-table-function-entirely-in-propensity-models).
> Fix [#1]()
=> replacing get_table() instances with run_query()

src/predictions/profiles_mlcorelib/py_native/id_stitcher/cluster_report.py, src/predictions/profiles_mlcorelib/py_native/id_stitcher/table_report.py, src/predictions/profiles_mlcorelib/wht/pythonWHT.py
In Audit id stitcher, we were making a few assumptions around the number of id types. For cases with a single id type, this is resulting in bugs. Fixed the issue by skipping the additional audit for such scenarios, as a single id type does not really need these steps. 
> Fix [#1]()
=> Skipping parts of id stitcher audit steps if only a single id type exists

.github/workflows/tests.yaml, samples/attribution_project/models/attribution.yaml, src/predictions/profiles_mlcorelib/py_native/attribution_report.py
> Ticket [Link](https://linear.app/rudderstack/issue/PRML-1129/make-campaign-vars-and-campaign-details-optional-in-attribution-models).
> Fix [#1]()
=> making campaign_vars and campaign_details optional in attribution model
